In [23]:
import pandas as pd
movies = pd.read_csv('movies.dat', delimiter='::',engine='python')
ratings = pd.read_csv('ratings.dat',delimiter='::',engine='python')
users = pd.read_csv('users.dat',delimiter='::',engine='python')

In [22]:
ratings

         UserID  MovieID  Rating  Timestamp
0             1     1193       5  978300760
1             1      661       3  978302109
2             1      914       3  978301968
3             1     3408       4  978300275
4             1     2355       5  978824291
5             1     1197       3  978302268
6             1     1287       5  978302039
7             1     2804       5  978300719
8             1      594       4  978302268
9             1      919       4  978301368
10            1      595       5  978824268
11            1      938       4  978301752
12            1     2398       4  978302281
13            1     2918       4  978302124
14            1     1035       5  978301753
15            1     2791       4  978302188
16            1     2687       3  978824268
17            1     2018       4  978301777
18            1     3105       5  978301713
19            1     2797       4  978302039
20            1     2321       3  978302205
21            1      720       3  978300760
22            1     1270       5  978300055
23            1      527       5  978824195
24            1     2340       3  978300103
25            1       48       5  978824351
26            1     1097       4  978301953
27            1     1721       4  978300055
28            1     1545       4  978824139
29            1      745       3  978824268
...         ...      ...     ...        ...
1000179    6040     2762       4  956704584
1000180    6040     1036       3  956715455
1000181    6040      508       4  956704972
1000182    6040     1041       4  957717678
1000183    6040     3735       4  960971654
1000184    6040     2791       4  956715569
1000185    6040     2794       1  956716438
1000186    6040      527       5  956704219
1000187    6040     2003       1  956716294
1000188    6040      535       4  964828734
1000189    6040     2010       5  957716795
1000190    6040     2011       4  956716113
1000191    6040     3751       4  964828782
1000192    6040     2019       5  956703977
1000193    6040      541       4  956715288
1000194    6040     1077       5  964828799
1000195    6040     1079       2  956715648
1000196    6040      549       4  956704746
1000197    6040     2020       3  956715288
1000198    6040     2021       3  956716374
1000199    6040     2022       5  956716207
1000200    6040     2028       5  956704519
1000201    6040     1080       4  957717322
1000202    6040     1089       4  956704996
1000203    6040     1090       3  956715518
1000204    6040     1091       1  956716541
1000205    6040     1094       5  956704887
1000206    6040      562       5  956704746
1000207    6040     1096       4  956715648
1000208    6040     1097       4  956715569

[1000209 rows x 4 columns]

In [36]:
merge_data = pd.merge(movies, pd.merge(ratings, users))

In [37]:
merge_data[0:11]

,MovieID,Title,Genres,UserID,Rating,Timestamp,Gender,Age,Occupation,Zip-code
0,1,Toy Story (1995),Animation|Children's|Comedy,1,5,978824268,F,1,10,48067
1,1,Toy Story (1995),Animation|Children's|Comedy,6,4,978237008,F,50,9,55117
2,1,Toy Story (1995),Animation|Children's|Comedy,8,4,978233496,M,25,12,11413
3,1,Toy Story (1995),Animation|Children's|Comedy,9,5,978225952,M,25,17,61614
4,1,Toy Story (1995),Animation|Children's|Comedy,10,5,978226474,F,35,1,95370
5,1,Toy Story (1995),Animation|Children's|Comedy,18,4,978154768,F,18,3,95825
6,1,Toy Story (1995),Animation|Children's|Comedy,19,5,978555994,M,1,10,48073
7,1,Toy Story (1995),Animation|Children's|Comedy,21,3,978139347,M,18,16,99353
8,1,Toy Story (1995),Animation|Children's|Comedy,23,4,978463614,M,35,0,90049
9,1,Toy Story (1995),Animation|Children's|Comedy,26,3,978130703,M,25,7,23112
10,1,Toy Story (1995),Animation|Children's|Comedy,28,3,978985309,F,25,1,14607

In [38]:
merge_data.sort_values(by=['Rating'],ascending=False,inplace=True)

In [40]:
merge_data[1:11]

,MovieID,Title,Genres,UserID,Rating,Timestamp,Gender,Age,Occupation,Zip-code
657724,2409,Rocky II (1979),Action|Drama,101,5,977578472,F,18,3,33314
244214,1012,Old Yeller (1957),Children's|Drama,447,5,976236279,F,45,11,55105
657745,2409,Rocky II (1979),Action|Drama,549,5,976119207,M,25,6,53217
657752,2409,Rocky II (1979),Action|Drama,684,5,975603281,M,25,4,27510
657764,2409,Rocky II (1979),Action|Drama,911,5,1046066544,M,50,0,98226
657773,2409,Rocky II (1979),Action|Drama,1035,5,974993708,M,18,2,15956
244200,1012,Old Yeller (1957),Children's|Drama,204,5,983855646,M,25,7,92123
657789,2409,Rocky II (1979),Action|Drama,1237,5,974833300,M,18,4,32720
657802,2409,Rocky II (1979),Action|Drama,1448,5,976126820,F,25,3,17522
657804,2409,Rocky II (1979),Action|Drama,1451,5,976519922,M,35,20,90012

In [42]:
merge_data['Genres'].value_counts()

Comedy                                           116883
Drama                                            111423
Comedy|Romance                                    42712
Comedy|Drama                                      42245
Drama|Romance                                     29170
Action|Thriller                                   26759
Horror                                            22563
Drama|Thriller                                    18248
Thriller                                          17851
Action|Adventure|Sci-Fi                           17783
Drama|War                                         14656
Action|Sci-Fi                                     14309
Action|Sci-Fi|Thriller                            13970
Action                                            12311
Action|Drama|War                                  12224
Crime|Drama                                       11870
Comedy|Drama|Romance                              11069
Action|Adventure                                  10446
Action|Drama                                      10382
Comedy|Horror                                      9681
Comedy|Sci-Fi                                      9311
Children's|Comedy                                  9077
Animation|Children's                               8851
Horror|Thriller                                    8649
Animation|Children's|Musical                       8220
Action|Adventure|Sci-Fi|Thriller                   7946
Animation|Children's|Comedy                        7870
Crime|Thriller                                     7467
Horror|Sci-Fi                                      7438
Action|Crime|Drama                                 6809
                                                  ...
Documentary|War                                     182
Animation|Children's|Comedy|Romance                 168
Documentary|Drama                                   168
Children's|Fantasy|Musical                          162
Adventure|Animation|Children's                      160
Adventure|Children's|Comedy|Fantasy|Romance         144
Action|Adventure|Animation|Children's|Fantasy       135
Children's|Drama|Fantasy                            130
Romance|War                                         130
Horror|Mystery                                      102
Drama|Film-Noir|Thriller                             98
Drama|Horror|Thriller                                85
Crime|Mystery                                        77
Adventure|Animation|Children's|Fantasy               68
Comedy|Mystery|Romance                               67
Comedy|Horror|Sci-Fi                                 65
Romance|Western                                      63
Drama|Romance|Sci-Fi                                 62
Adventure|Children's|Drama|Romance                   55
Action|Adventure|Children's|Fantasy                  44
Action|Adventure|Children's                          44
Comedy|Romance|Sci-Fi                                43
Animation|Mystery                                    41
Action|Comedy|Crime                                  41
Adventure|Musical|Romance                            30
Drama|Romance|Western                                29
Children's|Fantasy                                   27
Comedy|Film-Noir|Thriller                             5
Film-Noir|Horror                                      2
Fantasy                                               1
Name: Genres, dtype: int64